############
# Commands #
############
commands:
  reload:
    success: "&a[Pixel Mystery] Reload terminé."
    description: "Reload la configuration."
    usage: "/mystery reload"
  help:
    description: "Affiche ce message."
    usage: "/mystery help"
    title: "&bListe des commandes Pixel Mystery:"
    command: "&a%command% - %description%"
    commandAdmin: "&c%command% - %description%"
  build:
    success: "&a[Pixel Mystery] Utilise cette baguette magique pour créer et modifier de nouvelles arènes."
    description: "Reçoit la baguette magique."
    usage: "/mystery build"
  join:
    description: "Ouvre le menu pour rejoindre une partie."
    usage: "/mystery join"
  maps:
    description: "Affiche une liste des maps"
    usage: "/mystery maps"
  mapCreate:
    success: "&a[Pixel Mystery] Nouvelle map &b%map% &acréée."
    description: "Créer une map basé sur une sélection."
    usage: "/mystery map create <nom>"
  mapDelete:
    success: "&c[Pixel Mystery] Vous avez supprimé la map &b%map%&c."
    description: "Supprime une map."
    usage: "/mystery map delete <nom>"

#########
# Menus #
#########
menus:
  join:
    title: "Rejoindre une partie"
  maps:
    title: "Liste des maps"

############
# Messages #
############
messages:
  mapSettings:
    minPlayers: "&dJoueurs minimum: &e%value%"
    maxPlayers: "&dJoueurs maximum: &e%value%"
    meetingDuration: "&dTemps de discussion: &e%value% secondes"
    emergencyCooldown: "&dCooldown d'appel d'urgence: &e%value% secondes"
    emergencyLimit: "&dNombre d'appels d'urgence maximum: &e%value%"
    killCooldown: "&dCooldown de kill: &e%value% secondes"