name: PixelMystery
version: '${project.version}'
main: me.yukinox.pixelmystery.Plugin
api-version: 1.8
commands:
  mystery:
    description: "Commande Pixel Mystery de base."
    usage: "/mystery - Commande Pixel Mystery de base."
